language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install pyflakes
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 evobrain"
  - pyflakes evobrain
script:
  - coverage run manage.py test
  - coverage report
after_success:
  - coveralls

