language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 evobrain"
  - pyflakes -x W evobrain
script:
  - python manage.py test

